CREATE TABLE APP.Customer(ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,CUST_NAME  varchar(40) ,PASSWORD varchar(40));
CREATE TABLE APP.Question(ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY, word varchar(40), answer varchar(40), custId bigint, dateSubmitted timestamp)



